# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-04 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_timestamp', models.DateTimeField(blank=True, null=True)),
                ('clicked_timestamp', models.DateTimeField(blank=True, null=True)),
                ('interacted_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('link', models.URLField()),
                ('column', models.CharField(choices=[('BLO', 'blogs'), ('INT', 'international'), ('CUL', 'culture'), ('PAN', 'panorama'), ('REG', 'region'), ('TRA', 'travel'), ('SWI', 'Switzerland'), ('SPO', 'sports'), ('TEC', 'technology'), ('ECO', 'economic'), ('KNO', 'knowledge'), ('ZRH', 'Zurich'), ('ZHI', 'Zurich hints')], max_length=3)),
                ('target_group', models.CharField(blank=True, choices=[('YOU', 'young'), ('ADU', 'adult'), ('OLD', 'old')], max_length=3)),
                ('sent_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(blank=True, choices=[('YOU', 'young'), ('ADU', 'adult'), ('OLD', 'old')], max_length=3)),
                ('gender', models.CharField(blank=True, choices=[('m', 'man'), ('w', 'woman')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Message'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
